### PR TITLE
Upgrade date-fns@2

### PR DESCRIPTION
**Pull request by bengry**
[`date-fns@2` has been released](https://github.com/date-fns/date-fns/releases/tag/v2.0.0), and since `listr-verbose-renderer` is pinned on `^1.x.x`, it makes it hard for users `listr-verbose-renderer` to use `date-fns@2` simultaneously, due to conflicting packages.

This PR updates this dependency.

Note that this is a breaking change in `listr-verbose-renderer` for users who may have passed an invalid format (which previously worked) due to [a breaking change in `date-fns@2.0.0`, to better conform the unicode standard](https://github.com/date-fns/date-fns/blob/master/docs/unicodeTokens.md)

### CODE REVIEW

**Comment by bengry** [comment]
@SamVerschueren I'm not sure why the tests fail in Node 6. Can you please advise?

**Comment by SamVerschueren** [comment]
This is weird, according to the docs `hook-std` should be used differently 🤔 ...
https://github.com/sindresorhus/hook-std/tree/v1.1.0#usage

https://github.com/SamVerschueren/listr-verbose-renderer/blob/master/test/fixtures/utils.js

Looks like it should be something as this

```js
'use strict';
const hookStd = require('hook-std');
const stripAnsi = require('strip-ansi');

exports.testOutput = (t, expected) => {
	t.plan(t._test.planCount || expected.length);
	let i = 0;

	const promise = hookStd(actual => {
		t.is(stripAnsi(actual), `${expected[i++]}`);

		if (i === expected.length) {
			promise.unhook();
		}
	});
};
```

**Comment by bengry** [comment]
@SamVerschueren what's the difference between what's currently in https://github.com/SamVerschueren/listr-verbose-renderer/blob/master/test/fixtures/utils.js and the snippet you posted in https://github.com/SamVerschueren/listr-verbose-renderer/pull/8#issuecomment-528496855?

They look the same to me.

Also, note that I didn't change the file in the first place. I'm not sure if `master` would even pass the above test with any minor changes to it (there's no lock file in the repo, which may be the cause of the discrepency)

**Comment by SamVerschueren** [comment]
The difference is the `promise.unhook()` instead of just `unhook()`. Not sure why that would only fail on Node.js 6 though...

**Comment by bengry** [comment]
@SamVerschueren I missed that in the diff. Thanks.
I pushed the change to this branch and seems like Travis is now happy in all checked versions.

Is this something that you want to merge to `master` and release a new version for? I mentioned the reasoning behind this PR in the OP.

**Comment by maraisr** [comment]
Mega keen on this merge!

**Comment by bengry** [comment]
@SamVerschueren any update on this?

**Comment by SamVerschueren** [comment]
Sorry for the late replies and lack of response from my side. Released as `0.6.0`.

**Comment by SamVerschueren** [comment]
Thanks for working on this! 🎉

**Pull request merged**
